cmake_minimum_required(VERSION 3.5)

project(JZNodeEditor)

set(CMAKE_AUTOUIC ON)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)

find_package(QT NAMES Qt5 REQUIRED COMPONENTS widgets xml)
find_package(Qt${QT_VERSION_MAJOR} REQUIRED COMPONENTS core gui network widgets uitools serialport test designer printsupport DesignerComponents xml)
find_package(OpenCV 4 REQUIRED)

if (MSVC)
    add_compile_options(/execution-charset:utf-8)
    add_compile_options(/bigobj)
endif()

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/$<CONFIG>)

include_directories(./
    ./widgets
    ./script
    ./editor
    ./editor/ui
    ./editor/script
    ./editor/script/items   
    ${OpenCV_INCLUDE_DIRS})

set(JZNodeCore_SOURCES
    ${CMAKE_SOURCE_DIR}/LogManager.cpp
    ${CMAKE_SOURCE_DIR}/LogManager.h

    ${CMAKE_SOURCE_DIR}/script/JZParamItem.cpp
    ${CMAKE_SOURCE_DIR}/script/JZParamItem.h
    ${CMAKE_SOURCE_DIR}/script/JZProject.cpp
    ${CMAKE_SOURCE_DIR}/script/JZProject.h
    ${CMAKE_SOURCE_DIR}/script/JZProjectItem.cpp
    ${CMAKE_SOURCE_DIR}/script/JZProjectItem.h    
    ${CMAKE_SOURCE_DIR}/script/JZProjectTemplate.cpp
    ${CMAKE_SOURCE_DIR}/script/JZProjectTemplate.h
    ${CMAKE_SOURCE_DIR}/script/JZScriptFile.cpp
    ${CMAKE_SOURCE_DIR}/script/JZScriptFile.h
    ${CMAKE_SOURCE_DIR}/script/JZScriptItem.cpp
    ${CMAKE_SOURCE_DIR}/script/JZScriptItem.h
    ${CMAKE_SOURCE_DIR}/script/JZClassItem.cpp
    ${CMAKE_SOURCE_DIR}/script/JZClassItem.h
    ${CMAKE_SOURCE_DIR}/script/JZProjectFile.cpp
    ${CMAKE_SOURCE_DIR}/script/JZProjectFile.h
    ${CMAKE_SOURCE_DIR}/script/JZUiItem.cpp
    ${CMAKE_SOURCE_DIR}/script/JZUiItem.h
    ${CMAKE_SOURCE_DIR}/script/JZContainer.cpp
    ${CMAKE_SOURCE_DIR}/script/JZContainer.h
    ${CMAKE_SOURCE_DIR}/script/JZEvent.cpp
    ${CMAKE_SOURCE_DIR}/script/JZEvent.h
    ${CMAKE_SOURCE_DIR}/script/JZExpressionSolver.cpp
    ${CMAKE_SOURCE_DIR}/script/JZExpressionSolver.h
    ${CMAKE_SOURCE_DIR}/script/JZModule.cpp
    ${CMAKE_SOURCE_DIR}/script/JZModule.h
    ${CMAKE_SOURCE_DIR}/script/JZNode.cpp
    ${CMAKE_SOURCE_DIR}/script/JZNode.h
    ${CMAKE_SOURCE_DIR}/script/JZNodeFlow.cpp
    ${CMAKE_SOURCE_DIR}/script/JZNodeFlow.h
    ${CMAKE_SOURCE_DIR}/script/JZNodeBind.cpp
    ${CMAKE_SOURCE_DIR}/script/JZNodeBind.h
    ${CMAKE_SOURCE_DIR}/script/JZNodeBuilder.cpp
    ${CMAKE_SOURCE_DIR}/script/JZNodeBuilder.h
    ${CMAKE_SOURCE_DIR}/script/JZNodeCompiler.cpp
    ${CMAKE_SOURCE_DIR}/script/JZNodeCompiler.h    
    ${CMAKE_SOURCE_DIR}/script/JZNodeDebugClient.cpp
    ${CMAKE_SOURCE_DIR}/script/JZNodeDebugClient.h
    ${CMAKE_SOURCE_DIR}/script/JZNodeDebugPacket.cpp
    ${CMAKE_SOURCE_DIR}/script/JZNodeDebugPacket.h
    ${CMAKE_SOURCE_DIR}/script/JZNodeDebugServer.cpp
    ${CMAKE_SOURCE_DIR}/script/JZNodeDebugServer.h
    ${CMAKE_SOURCE_DIR}/script/JZNodeEngine.cpp
    ${CMAKE_SOURCE_DIR}/script/JZNodeEngine.h
    ${CMAKE_SOURCE_DIR}/script/JZNodeEnum.cpp
    ${CMAKE_SOURCE_DIR}/script/JZNodeEnum.h
    ${CMAKE_SOURCE_DIR}/script/JZNodeEvent.cpp
    ${CMAKE_SOURCE_DIR}/script/JZNodeEvent.h
    ${CMAKE_SOURCE_DIR}/script/JZNodeExpression.cpp
    ${CMAKE_SOURCE_DIR}/script/JZNodeExpression.h
    ${CMAKE_SOURCE_DIR}/script/JZNodeFactory.cpp
    ${CMAKE_SOURCE_DIR}/script/JZNodeFactory.h
    ${CMAKE_SOURCE_DIR}/script/JZNodeFunction.cpp
    ${CMAKE_SOURCE_DIR}/script/JZNodeFunction.h
    ${CMAKE_SOURCE_DIR}/script/JZNodeFunctionDefine.cpp
    ${CMAKE_SOURCE_DIR}/script/JZNodeFunctionDefine.h
    ${CMAKE_SOURCE_DIR}/script/JZNodeFunctionManager.cpp
    ${CMAKE_SOURCE_DIR}/script/JZNodeFunctionManager.h
    ${CMAKE_SOURCE_DIR}/script/JZScriptEnvironment.cpp
    ${CMAKE_SOURCE_DIR}/script/JZScriptEnvironment.h
    ${CMAKE_SOURCE_DIR}/script/JZNodeInit.cpp
    ${CMAKE_SOURCE_DIR}/script/JZNodeInit.h
    ${CMAKE_SOURCE_DIR}/script/JZNodeIR.cpp
    ${CMAKE_SOURCE_DIR}/script/JZNodeIR.h
    ${CMAKE_SOURCE_DIR}/script/JZNodeLangServer.cpp
    ${CMAKE_SOURCE_DIR}/script/JZNodeLangServer.h
    ${CMAKE_SOURCE_DIR}/script/JZNodeMeta.cpp
    ${CMAKE_SOURCE_DIR}/script/JZNodeMeta.h
    ${CMAKE_SOURCE_DIR}/script/JZNodeObject.cpp
    ${CMAKE_SOURCE_DIR}/script/JZNodeObject.h
    ${CMAKE_SOURCE_DIR}/script/JZNodeObjectParser.cpp
    ${CMAKE_SOURCE_DIR}/script/JZNodeObjectParser.h
    ${CMAKE_SOURCE_DIR}/script/JZNodeOperator.cpp
    ${CMAKE_SOURCE_DIR}/script/JZNodeOperator.h
    ${CMAKE_SOURCE_DIR}/script/JZNodePin.cpp
    ${CMAKE_SOURCE_DIR}/script/JZNodePin.h
    ${CMAKE_SOURCE_DIR}/script/JZNodeProgram.cpp
    ${CMAKE_SOURCE_DIR}/script/JZNodeProgram.h
    ${CMAKE_SOURCE_DIR}/script/JZNodeProgramDumper.cpp
    ${CMAKE_SOURCE_DIR}/script/JZNodeProgramDumper.h
    ${CMAKE_SOURCE_DIR}/script/JZNodeQtWrapper.cpp
    ${CMAKE_SOURCE_DIR}/script/JZNodeQtWrapper.h
    ${CMAKE_SOURCE_DIR}/script/JZNodeType.cpp
    ${CMAKE_SOURCE_DIR}/script/JZNodeType.h    
    ${CMAKE_SOURCE_DIR}/script/JZNodeUtils.cpp
    ${CMAKE_SOURCE_DIR}/script/JZNodeUtils.h
    ${CMAKE_SOURCE_DIR}/script/JZNodeValue.cpp
    ${CMAKE_SOURCE_DIR}/script/JZNodeValue.h
    ${CMAKE_SOURCE_DIR}/script/JZNodeVariableBind.cpp
    ${CMAKE_SOURCE_DIR}/script/JZNodeVariableBind.h
    ${CMAKE_SOURCE_DIR}/script/JZNodeVM.cpp
    ${CMAKE_SOURCE_DIR}/script/JZNodeVM.h
    ${CMAKE_SOURCE_DIR}/script/JZRegExpHelp.cpp
    ${CMAKE_SOURCE_DIR}/script/JZRegExpHelp.h
    ${CMAKE_SOURCE_DIR}/script/JZScriptBuildInFunction.cpp
    ${CMAKE_SOURCE_DIR}/script/JZScriptBuildInFunction.h   
    ${CMAKE_SOURCE_DIR}/script/JZScriptConvert.cpp
    ${CMAKE_SOURCE_DIR}/script/JZScriptConvert.h  
    ${CMAKE_SOURCE_DIR}/script/angelscript/as_parser.cpp
    ${CMAKE_SOURCE_DIR}/script/angelscript/as_parser.h
    ${CMAKE_SOURCE_DIR}/script/angelscript/as_scriptcode.cpp
    ${CMAKE_SOURCE_DIR}/script/angelscript/as_scriptcode.h
    ${CMAKE_SOURCE_DIR}/script/angelscript/as_scriptnode.cpp
    ${CMAKE_SOURCE_DIR}/script/angelscript/as_scriptnode.h
    ${CMAKE_SOURCE_DIR}/script/angelscript/as_tokendef.h
    ${CMAKE_SOURCE_DIR}/script/angelscript/as_tokenizer.cpp
    ${CMAKE_SOURCE_DIR}/script/angelscript/as_tokenizer.h    

    #runtime
    ${CMAKE_SOURCE_DIR}/runtime/JZNodeUiLoader.cpp
    ${CMAKE_SOURCE_DIR}/runtime/JZNodeUiLoader.h
    #modbus    
    ${CMAKE_SOURCE_DIR}/modules/modbus/JZModuleModbus.cpp
    ${CMAKE_SOURCE_DIR}/modules/modbus/JZModuleModbus.h
     
    #opencv
    ${CMAKE_SOURCE_DIR}/modules/opencv/JZModuleOpencv.h
    ${CMAKE_SOURCE_DIR}/modules/opencv/JZModuleOpencv.cpp    
    ${CMAKE_SOURCE_DIR}/modules/opencv/CvMatAndQImage.h
    ${CMAKE_SOURCE_DIR}/modules/opencv/CvMatAndQImage.cpp
    ${CMAKE_SOURCE_DIR}/modules/opencv/CvToQt.h
    ${CMAKE_SOURCE_DIR}/modules/opencv/CvToQt.cpp
    ${CMAKE_SOURCE_DIR}/modules/opencv/JZYolo.h
    ${CMAKE_SOURCE_DIR}/modules/opencv/JZYolo.cpp
    ${CMAKE_SOURCE_DIR}/modules/opencv/JZYoloView.h
    ${CMAKE_SOURCE_DIR}/modules/opencv/JZYoloView.cpp
    #camera
    ${CMAKE_SOURCE_DIR}/modules/camera/JZModuleCamera.h
    ${CMAKE_SOURCE_DIR}/modules/camera/JZModuleCamera.cpp
    ${CMAKE_SOURCE_DIR}/modules/camera/JZCamera.h
    ${CMAKE_SOURCE_DIR}/modules/camera/JZCamera.cpp
    ${CMAKE_SOURCE_DIR}/modules/camera/JZCameraFile.h
    ${CMAKE_SOURCE_DIR}/modules/camera/JZCameraFile.cpp
    
    #3rd
    ${CMAKE_SOURCE_DIR}/3rd/JZCommon/jzNet/JZNetClient.cpp
    ${CMAKE_SOURCE_DIR}/3rd/JZCommon/jzNet/JZNetClient.h
    ${CMAKE_SOURCE_DIR}/3rd/JZCommon/jzNet/JZNetDataManager.cpp
    ${CMAKE_SOURCE_DIR}/3rd/JZCommon/jzNet/JZNetDataManager.h
    ${CMAKE_SOURCE_DIR}/3rd/JZCommon/jzNet/JZNetPack.cpp
    ${CMAKE_SOURCE_DIR}/3rd/JZCommon/jzNet/JZNetPack.h
    ${CMAKE_SOURCE_DIR}/3rd/JZCommon/jzNet/JZNetServer.cpp
    ${CMAKE_SOURCE_DIR}/3rd/JZCommon/jzNet/JZNetServer.h
    ${CMAKE_SOURCE_DIR}/3rd/JZCommon/jzModbus/JZModbusClient.cpp
    ${CMAKE_SOURCE_DIR}/3rd/JZCommon/jzModbus/JZModbusClient.h
    ${CMAKE_SOURCE_DIR}/3rd/JZCommon/jzModbus/JZModbusContext.cpp
    ${CMAKE_SOURCE_DIR}/3rd/JZCommon/jzModbus/JZModbusContext.h
    ${CMAKE_SOURCE_DIR}/3rd/JZCommon/jzModbus/JZModbusDefine.cpp
    ${CMAKE_SOURCE_DIR}/3rd/JZCommon/jzModbus/JZModbusDefine.h
    ${CMAKE_SOURCE_DIR}/3rd/JZCommon/jzModbus/JZModbusMaster.cpp
    ${CMAKE_SOURCE_DIR}/3rd/JZCommon/jzModbus/JZModbusMaster.h
    ${CMAKE_SOURCE_DIR}/3rd/JZCommon/jzModbus/JZModbusParam.cpp
    ${CMAKE_SOURCE_DIR}/3rd/JZCommon/jzModbus/JZModbusParam.h
    ${CMAKE_SOURCE_DIR}/3rd/JZCommon/jzModbus/JZModbusRtu.cpp
    ${CMAKE_SOURCE_DIR}/3rd/JZCommon/jzModbus/JZModbusRtu.h
    ${CMAKE_SOURCE_DIR}/3rd/JZCommon/jzModbus/JZModbusServer.cpp
    ${CMAKE_SOURCE_DIR}/3rd/JZCommon/jzModbus/JZModbusServer.h
    ${CMAKE_SOURCE_DIR}/3rd/JZCommon/jzModbus/JZModbusSlaver.cpp
    ${CMAKE_SOURCE_DIR}/3rd/JZCommon/jzModbus/JZModbusSlaver.h
    ${CMAKE_SOURCE_DIR}/3rd/JZCommon/jzModbus/JZModbusTcp.cpp
    ${CMAKE_SOURCE_DIR}/3rd/JZCommon/jzModbus/JZModbusTcp.h
    ${CMAKE_SOURCE_DIR}/3rd/JZCommon/jzWidgets/JZImageView.cpp
    ${CMAKE_SOURCE_DIR}/3rd/JZCommon/jzWidgets/JZImageView.h    
    ${CMAKE_SOURCE_DIR}/3rd/JZCommon/jzCommon/JZLogManager.cpp
    ${CMAKE_SOURCE_DIR}/3rd/JZCommon/jzCommon/JZLogManager.h
)

set(JZNodeEditor_SOURCES
    JZNodeEditor.qrc
    main.cpp      
    mainTask.cpp    
    mainTask.h    
    LogWidget.cpp
    LogWidget.h    
    mainwindow.cpp
    mainwindow.h
    UiCommon.cpp
    UiCommon.h    
    editor/JZEditor.cpp
    editor/JZEditor.h
    editor/JZEditorGlobal.cpp
    editor/JZEditorGlobal.h
    editor/JZNewFileDialog.cpp
    editor/JZNewFileDialog.h
    editor/JZNewFileDialog.ui
    editor/JZNewProjectDialog.cpp
    editor/JZNewProjectDialog.h
    editor/JZNewProjectDialog.ui
    editor/JZProjectSettingDialog.cpp
    editor/JZProjectSettingDialog.h
    editor/JZProjectTree.cpp
    editor/JZProjectTree.h
    editor/JZEditorUtils.cpp
    editor/JZEditorUtils.h
    editor/script/JZNodeAutoRunThread.cpp
    editor/script/JZNodeAutoRunThread.h
    editor/script/JZNodeAutoRunWidget.cpp
    editor/script/JZNodeAutoRunWidget.h    
    editor/script/JZNodeBreakPointWidget.cpp
    editor/script/JZNodeBreakPointWidget.h
    editor/script/JZNodeBuildThread.cpp
    editor/script/JZNodeBuildThread.h
    editor/script/JZNodeEditor.cpp
    editor/script/JZNodeEditor.h
    editor/script/JZNodeEditorManager.cpp
    editor/script/JZNodeEditorManager.h
    editor/script/JZNodeExprEditDialog.cpp
    editor/script/JZNodeExprEditDialog.h
    editor/script/JZNodeFlagEditDialog.cpp
    editor/script/JZNodeFlagEditDialog.h
    editor/script/JZNodeFuctionEditDialog.cpp
    editor/script/JZNodeFuctionEditDialog.h
    editor/script/JZNodeFuctionEditDialog.ui    
    editor/script/JZNodeGroupEditDialog.cpp
    editor/script/JZNodeGroupEditDialog.h
    editor/script/JZNodeGroupEditDialog.ui    
    editor/script/JZNodeLayout.cpp
    editor/script/JZNodeLayout.h
    editor/script/JZNodeLocalParamEditDialog.cpp
    editor/script/JZNodeLocalParamEditDialog.h
    editor/script/JZNodeMemberSelectDialog.cpp
    editor/script/JZNodeMemberSelectDialog.h
    editor/script/JZNodeMemberSelectDialog.ui
    editor/script/JZNodePanel.cpp
    editor/script/JZNodePanel.h
    editor/script/JZNodeParamBindEditDialog.cpp
    editor/script/JZNodeParamBindEditDialog.h
    editor/script/JZNodeParamBindEditDialog.ui
    editor/script/JZNodeParamEditor.cpp
    editor/script/JZNodeParamEditor.h
    editor/script/JZNodeParamEditor.ui
    editor/script/JZNodePinWidget.cpp
    editor/script/JZNodePinWidget.h
    editor/script/JZNodeParamEditWidget.cpp
    editor/script/JZNodeParamEditWidget.h
    editor/script/JZNodeParamDisplayWidget.cpp
    editor/script/JZNodeParamDisplayWidget.h        
    editor/script/JZNodePropertyEditor.cpp
    editor/script/JZNodePropertyEditor.h
    editor/script/JZNodeScene.cpp
    editor/script/JZNodeScene.h
    editor/script/JZNodeSlotEditDialog.cpp
    editor/script/JZNodeSlotEditDialog.h
    editor/script/JZNodeStack.cpp
    editor/script/JZNodeStack.h
    editor/script/JZNodeTypeDialog.ui
    editor/script/JZNodeTypeHelper.cpp
    editor/script/JZNodeTypeHelper.h
    editor/script/JZNodeView.cpp
    editor/script/JZNodeView.h
    editor/script/JZNodeViewCommand.cpp
    editor/script/JZNodeViewCommand.h
    editor/script/JZNodeViewMap.cpp
    editor/script/JZNodeViewMap.h
    editor/script/JZNodeFlowPanel.cpp
    editor/script/JZNodeFlowPanel.h
    editor/script/JZNodeVirtualFuctionEditDialog.cpp
    editor/script/JZNodeVirtualFuctionEditDialog.h
    editor/script/JZNodeWatch.cpp
    editor/script/JZNodeWatch.h
    editor/script/JZProcess.cpp
    editor/script/JZProcess.h   
    editor/script/JZNodeClassEditDialog.ui
    editor/script/JZNodeClassEditDialog.cpp
    editor/script/JZNodeClassEditDialog.h       
    editor/script/items/JZNodeBaseItem.cpp
    editor/script/items/JZNodeBaseItem.h
    editor/script/items/JZNodeGroupItem.cpp
    editor/script/items/JZNodeGroupItem.h
    editor/script/items/JZNodeLineItem.cpp
    editor/script/items/JZNodeLineItem.h
    editor/script/items/JZNodeGraphItem.cpp
    editor/script/items/JZNodeGraphItem.h
    editor/script/items/JZNodeFlowItem.cpp
    editor/script/items/JZNodeFlowItem.h
    editor/script/items/JZNodeOperatorItem.cpp
    editor/script/items/JZNodeOperatorItem.h    
    editor/ui/formresizer.cpp
    editor/ui/formresizer.h
    editor/ui/JZDesignerEditor.cpp
    editor/ui/JZDesignerEditor.h
    editor/ui/JZDesignerFormWindow.cpp
    editor/ui/JZDesignerFormWindow.h
    editor/ui/JZDesinger.cpp
    editor/ui/JZDesinger.h
    editor/ui/JZMenuExtension.cpp
    editor/ui/JZMenuExtension.h
    editor/ui/JZNodeIntegration.cpp
    editor/ui/JZNodeIntegration.h
    editor/ui/JZUiEditor.cpp
    editor/ui/JZUiEditor.h
    editor/ui/JZWidgetCollectionInterface.cpp
    editor/ui/JZWidgetCollectionInterface.h
    editor/ui/sizehandlerect.cpp
    editor/ui/sizehandlerect.h
    editor/ui/widgethostconstants.h
     
    widgets/JZAboutDialog.cpp
    widgets/JZAboutDialog.h
    widgets/JZBaseDialog.cpp
    widgets/JZBaseDialog.h
    widgets/JZSearchTreeWidget.cpp
    widgets/JZSearchTreeWidget.h  
    widgets/JZImageLabel.cpp 
    widgets/JZImageLabel.h     

    #modbus        
    ${CMAKE_SOURCE_DIR}/modules/modbus/JZModuleModbusEditor.cpp
    ${CMAKE_SOURCE_DIR}/modules/modbus/JZModuleModbusEditor.h
    ${CMAKE_SOURCE_DIR}/modules/modbus/JZModbusConfigDialog.cpp
    ${CMAKE_SOURCE_DIR}/modules/modbus/JZModbusConfigDialog.h
    ${CMAKE_SOURCE_DIR}/modules/modbus/JZModbusConfigDialog.ui
    ${CMAKE_SOURCE_DIR}/modules/modbus/JZModbusSimulator.cpp
    ${CMAKE_SOURCE_DIR}/modules/modbus/JZModbusSimulator.h
    ${CMAKE_SOURCE_DIR}/modules/modbus/JZModbusTemplateDialog.cpp
    ${CMAKE_SOURCE_DIR}/modules/modbus/JZModbusTemplateDialog.h    
    #opencv    
    ${CMAKE_SOURCE_DIR}/modules/opencv/JZModuleOpencvEditor.h
    ${CMAKE_SOURCE_DIR}/modules/opencv/JZModuleOpencvEditor.cpp            
    #camera    
    ${CMAKE_SOURCE_DIR}/modules/camera/JZModuleCameraEditor.h
    ${CMAKE_SOURCE_DIR}/modules/camera/JZModuleCameraEditor.cpp       
    
    #3rd    
    3rd/JZCommon/jzWidgets/JZPropertyBrowser.cpp
    3rd/JZCommon/jzWidgets/JZPropertyBrowser.h
    3rd/JZCommon/jzWidgets/JZPropertyWidget.cpp
    3rd/JZCommon/jzWidgets/JZPropertyWidget.h    
)

add_executable(JZNodeEditor ${JZNodeEditor_SOURCES} ${JZNodeCore_SOURCES})
target_link_libraries(JZNodeEditor Qt${QT_VERSION_MAJOR}::Widgets
    Qt${QT_VERSION_MAJOR}::Network          
    Qt${QT_VERSION_MAJOR}::SerialPort      
    Qt${QT_VERSION_MAJOR}::PrintSupport
    Qt${QT_VERSION_MAJOR}::Xml
    Qt${QT_VERSION_MAJOR}::Designer
    Qt${QT_VERSION_MAJOR}::DesignerComponents
    Qt${QT_VERSION_MAJOR}::UiTools
    ${OpenCV_LIBRARIES})    
set_target_properties(JZNodeEditor PROPERTIES
    WIN32_EXECUTABLE TRUE
)

add_subdirectory(tests)